# Generated by Django 5.2.17 on 2026-08-19 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Full program name, e.g. 'BS Information Technology'.", max_length=150)),
                ('short_name', models.CharField(help_text="Short code shown throughout the site, e.g. 'BSIT'.", max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short paragraph about this program (helps SEO too).')),
                ('total_semesters', models.PositiveSmallIntegerField(default=8, help_text='How many semesters this program has (usually 8 for a 4-year degree).')),
                ('icon', models.ImageField(blank=True, help_text='Small square icon/logo shown on the program card (optional).', null=True, upload_to='programs/icons/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this program from the public site.')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(help_text='1, 2, 3 ...')),
                ('name', models.CharField(blank=True, help_text="Optional custom label. Defaults to 'Semester <number>'.", max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['program', 'number'],
                'unique_together': {('program', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Optional subject code, e.g. CS-301.', max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('credit_hours', models.CharField(blank=True, help_text="e.g. '3(3-0)'", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Short overview of what this subject covers.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='subjects/covers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name'],
                'unique_together': {('semester', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position of this topic in the subject outline.')),
                ('content', models.TextField(blank=True, help_text='Main study notes / explanation for this topic.')),
                ('youtube_url', models.URLField(blank=True, help_text='Optional YouTube video link that explains this topic.')),
                ('document_link', models.URLField(blank=True, help_text='Optional shareable Google Drive (or other) link to a document/slide for this topic, e.g. lecture slides or a handout.')),
                ('is_published', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'id'],
                'unique_together': {('subject', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image, OR fill in the Drive link field below instead.', null=True, upload_to='topics/images/')),
                ('drive_link', models.URLField(blank=True, help_text='Shareable Google Drive (or other) image link, used if no file is uploaded.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academics.topic')),
            ],
            options={
                'verbose_name': 'Topic image',
                'verbose_name_plural': 'Topic images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(help_text='e.g. 2023')),
                ('exam_type', models.CharField(choices=[('mid', 'Mid Term'), ('final', 'Final Term'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='final', max_length=20)),
                ('paper_drive_link', models.URLField(help_text='Shareable Google Drive link to the scanned/photographed question paper.')),
                ('solution_type', models.CharField(choices=[('none', 'No solution yet'), ('text', 'Written solution (text)'), ('image', 'Solution image(s) / Drive link')], default='none', max_length=10)),
                ('solution_text', models.TextField(blank=True, help_text="Used when solution type is 'Written solution (text)'.")),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='pastpapers/solutions/')),
                ('solution_drive_link', models.URLField(blank=True, help_text='Used when the solution is one or more images/photos kept on Drive.')),
                ('is_published', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Past Paper',
                'verbose_name_plural': 'Past Papers',
                'ordering': ['-year', 'exam_type'],
                'unique_together': {('subject', 'year', 'exam_type')},
            },
        ),
    ]
