# Generated by Django 5.2.17 on 2026-08-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='icon',
        ),
    ]
