# Generated by Django 5.2.17 on 2026-08-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_program_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaper',
            name='solution_image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='topicimage',
            name='image',
        ),
        migrations.AddField(
            model_name='program',
            name='icon_drive_link',
            field=models.URLField(blank=True, help_text='Shareable Google Drive (or other) link to a square icon/logo image for this program (optional).'),
        ),
        migrations.AddField(
            model_name='subject',
            name='cover_image_drive_link',
            field=models.URLField(blank=True, help_text="Shareable Google Drive (or other) link to a cover image for this subject (optional — shown on the subject's page)."),
        ),
        migrations.AlterField(
            model_name='topicimage',
            name='drive_link',
            field=models.URLField(help_text='Shareable Google Drive (or other) link to this image.'),
        ),
    ]
