# Generated by Django 5.2.17 on 2026-08-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='content',
            field=models.TextField(blank=True, help_text='Text explanation for this subtopic.'),
        ),
        migrations.CreateModel(
            name='AIProviderUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI Provider Usage',
                'verbose_name_plural': 'AI Provider Usage',
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
