# Generated by Django 5.2.17 on 2026-08-22 08:29

import django.db.models.deletion
from django.db import migrations, models
def populate_subtopic_slugs(apps, schema_editor):
    SubTopic = apps.get_model('academics', 'SubTopic')
    from django.utils.text import slugify
    seen = {}
    for st in SubTopic.objects.all().order_by('id'):
        base = slugify(st.title)[:270] or f"subtopic-{st.id}"
        key = (st.topic_id, base)
        count = seen.get(key, 0)
        seen[key] = count + 1
        final_slug = base if count == 0 else f"{base}-{count}"
        st.slug = final_slug
        st.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subtopic_content_aiproviderusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='document_link',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
                migrations.RunPython(populate_subtopic_slugs, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'slug')},
        ),
        migrations.CreateModel(
            name='SubTopicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.URLField(help_text='A YouTube video link that explains this subtopic.')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.subtopic')),
            ],
            options={
                'verbose_name': 'Subtopic video',
                'verbose_name_plural': 'Subtopic videos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_link', models.URLField(help_text='Shareable Google Drive (or other) link to this document/PDF.')),
                ('title', models.CharField(blank=True, help_text="e.g. 'Lecture slides', 'Handout PDF'.", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.topic')),
            ],
            options={
                'verbose_name': 'Topic document',
                'verbose_name_plural': 'Topic documents',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.URLField(help_text='A YouTube video link that explains this topic.')),
                ('title', models.CharField(blank=True, help_text='Optional label shown above the video.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.topic')),
            ],
            options={
                'verbose_name': 'Topic video',
                'verbose_name_plural': 'Topic videos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
