# Generated by Django 5.2.17 on 2026-08-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_topic_document_link_remove_topic_youtube_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_link', models.URLField(help_text='Shareable Google Drive (or other) link to this document/PDF.')),
                ('title', models.CharField(blank=True, help_text="e.g. 'Lecture slides', 'Handout PDF'.", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.subtopic')),
            ],
            options={
                'verbose_name': 'Subtopic document',
                'verbose_name_plural': 'Subtopic documents',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubTopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_link', models.URLField(help_text='Shareable Google Drive (or other) link to this image.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academics.subtopic')),
            ],
            options={
                'verbose_name': 'Subtopic image',
                'verbose_name_plural': 'Subtopic images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
