# Generated by Django 5.2.17 on 2026-08-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subtopicdocument_subtopicimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from the question paper image/PDF via OCR (not shown on the frontend yet).'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='solution_text',
            field=models.TextField(blank=True, help_text="Used when solution type is 'Written solution (text)'. You can generate this from the question paper using the OCR + AI tools above (near the Drive link field)."),
        ),
    ]
