# Generated by Django 5.2.17 on 2026-08-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_pastpaper_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_drive_link',
            field=models.URLField(blank=True, help_text='Shareable Google Drive link to the full book/PDF/Doc for this subject (optional).'),
        ),
    ]
