# Generated by Django 5.2.17 on 2026-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatvisitor_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('first_visited', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-visit_count'],
            },
        ),
    ]
